[JS] Publish (#60)

diff --git a/.github/workflows/JS_build_test_publish.yml b/.github/workflows/JS_build_test_publish.yml
--- a/.github/workflows/JS_build_test_publish.yml
+++ b/.github/workflows/JS_build_test_publish.yml
@@ -2,7 +2,7 @@ name: "[JS] Build, Test, and Publish"
 
 env:
   DEBUG: napi:*
-  APP_NAME: optify-config
+  APP_NAME: config
   CARGO_TERM_COLOR: always
   MACOSX_DEPLOYMENT_TARGET: '10.13'
 permissions:
@@ -137,7 +137,7 @@ jobs:
           path: ./js/optify-config/${{ env.APP_NAME }}.*.node
           if-no-files-found: error
   build-freebsd:
-    # Disable for now because it gives too many installation errors such as when trying to install `yarn`.
+    # Disabled for now because it gives too many installation errors such as when trying to install `yarn`.
     if: ${{ false }}
     runs-on: macos-13
     name: "[FreeBSD] Build"
@@ -378,7 +378,12 @@ jobs:
           name: bindings-aarch64-apple-darwin
           path: ./js/optify-config/artifacts
       - name: Combine binaries
-        run: yarn universal
+        run: |
+          set -ex
+          ls -lRh ./artifacts/
+          yarn universal
+          ls -lh .
+        shell: bash
         working-directory: ./js/optify-config
       - name: Upload artifact
         uses: actions/upload-artifact@v4
@@ -424,25 +429,14 @@ jobs:
       - name: Publish
         if: github.ref == 'refs/heads/main'
         shell: bash
-        # It probably just fails if the gem is already published.
+        # It probably just fails if the package is already published.
         # We want to only be lenient for the `npm publish`, but we would still want to clearly see that an issue happened during the run.
         continue-on-error: true
-        # FIXME: What is the point of checking the commit message? Seems super hacky.
-        # We probably always want to publish the release for main.
         run: |
           set -ex
           npm config set provenance true
-          if git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$";
-          then
-            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
-            npm publish --access public
-          elif git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+";
-          then
-            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
-            npm publish --tag next --access public
-          else
-            echo "Not a release, skipping publish"
-          fi
+          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
+          npm publish --access public
         working-directory: ./js/optify-config
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
