[Ruby] Publish source gem

diff --git a/.github/workflows/ruby_cross-build.yml b/.github/workflows/ruby_cross-build.yml
--- a/.github/workflows/ruby_cross-build.yml
+++ b/.github/workflows/ruby_cross-build.yml
@@ -109,3 +109,36 @@ jobs:
         sha256sum "${gem_path}"
       env:
         GEM_HOST_API_KEY: '${{ secrets.RUBYGEMS_API_KEY }}'
+
+  # Publish a gem with the Rust source code.
+  source-gem:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v4
+
+    # setup-ruby also runs `bundle install`.
+    # It uses the Ruby version from .ruby-version.
+    - uses: ruby/setup-ruby@v1
+      name: "Setup"
+      with:
+        bundler-cache: true
+        working-directory: ./ruby/optify
+
+    - name: Build gem
+      run: bundle exec rake build
+      working-directory: ./ruby/optify
+
+    - name: "Publish"
+      if: github.ref == 'refs/heads/main'
+      shell: bash
+      # It probably just fails if the gem is already published.
+      # We want to only be lenient for the `gem push`, but we would still want to clearly see that an issue happened during the run.
+      continue-on-error: true
+      run: |
+        set -ex
+        gem_path="pkg/*.gem"
+        ls -lh "${gem_path}"
+        gem push "${gem_path}"
+        sha256sum "${gem_path}"
+      env:
+        GEM_HOST_API_KEY: '${{ secrets.RUBYGEMS_API_KEY }}'
