CI: Publish

diff --git a/.github/workflows/ruby_build_test.yml b/.github/workflows/ruby_build_test.yml
--- a/.github/workflows/ruby_build_test.yml
+++ b/.github/workflows/ruby_build_test.yml
@@ -88,6 +88,28 @@ jobs:
       run: bundle exec rake test
       working-directory: ./ruby/optify-from_hash
 
+    - name: "[Ruby][from_hash] Build"
+      if: github.ref != 'refs/heads/main' && matrix.os == 'ubuntu-latest'
+      shell: bash
+      run: |
+        set -ex
+        bundle exec rake build
+      working-directory: ./ruby/optify-from_hash
+      env:
+        GEM_HOST_API_KEY: '${{ secrets.RUBYGEMS_API_KEY }}'
+
+    - name: "[Ruby][from_hash] Publish"
+      if: github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest'
+      # It probably just fails if the gem is already published.
+      continue-on-error: true
+      shell: bash
+      run: |
+        set -ex
+        bundle exec rake release
+      working-directory: ./ruby/optify-from_hash
+      env:
+        GEM_HOST_API_KEY: '${{ secrets.RUBYGEMS_API_KEY }}'
+
     # Gem: optify
     - name: "[Ruby] Check Ruby version"
       shell: bash
